name: Linux Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libudev-dev \
          libopenal-dev \
          libvorbis-dev \
          libflac-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxi-dev \
          libfreetype-dev
          
      - name: Install dependencies
        run: sudo apt install cmake libsfml-dev xvfb -y

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Run
        run: xvfb-run -a timeout 3 ./Game || true
