name: Linux Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install cmake libsfml-dev xvfb -y

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Run
        run: xvfb-run -a timeout 3 ./Game || true
