name: Windows Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build
          cmake --build build --config Release

      - name: Check executable exists
        shell: pwsh
        run: |
          if (Test-Path .\Release\Game.exe) {
            Write-Host "Game.exe found"
          } else {
            Write-Host "Game.exe not found"
            exit 1
          }
